export const getCustomersData = () => [
  {
    Id: 1,
    firstName: "Sarah",
    lastName: "Johnson",
    email: "sarah@healthysmilesdentistry.com.au",
    phone: "03 9876 5432",
    company: "Healthy Smiles Sleep Dentistry Melbourne",
    serviceId: 2,
    price: 497,
    billingFrequency: "monthly",
    quantity: 1,
    startDate: "2024-01-15",
    contractDuration: 12,
    status: "active",
    paymentStatus: "Paid",
    notes: "High-value client with excellent payment history"
  },
  {
    Id: 2,
    firstName: "Michael",
    lastName: "Chen",
    email: "michael@healthysmilesdentistry.com.au",
    phone: "03 9876 5433",
    company: "Healthy Smiles Sleep Dentistry Melbourne",
    serviceId: 1,
    price: 599,
    billingFrequency: "monthly",
    quantity: 1,
    startDate: "2024-01-15",
    contractDuration: 12,
    status: "active",
    paymentStatus: "Paid",
    notes: "Uses both MapBooster and CRM services"
  },
  {
    Id: 3,
    firstName: "Emma",
    lastName: "Wilson",
    email: "emma@wellbeingchiro.com.au",
    phone: "03 9654 3210",
    company: "Wellbeing Chiropractic Hawthorn",
    serviceId: 2,
    price: 155,
    billingFrequency: "monthly",
    quantity: 6,
    startDate: "2024-02-01",
    contractDuration: 24,
    status: "active",
    paymentStatus: "Paid",
    notes: "Multi-location client with 6 locations"
  },
  {
    Id: 4,
    firstName: "David",
    lastName: "Thompson",
    email: "david@wellbeingchiro.com.au",
    phone: "03 9654 3211",
    company: "Wellbeing Chiropractic Hawthorn",
    serviceId: 1,
    price: 1599,
    billingFrequency: "monthly",
    quantity: 1,
    startDate: "2024-02-01",
    contractDuration: 24,
    status: "active",
    paymentStatus: "Paid",
    notes: "Enterprise CRM package for multi-location practice"
  },
  {
    Id: 5,
    firstName: "Lisa",
    lastName: "Martinez",
    email: "lisa@evansroaddental.com.au",
    phone: "03 9432 1098",
    company: "Evans Road Dental Care",
    serviceId: 1,
    price: 499,
    billingFrequency: "monthly",
    quantity: 1,
    startDate: "2024-01-20",
    contractDuration: 12,
    status: "active",
    paymentStatus: "Paid",
    notes: "Steady client with consistent payments"
  },
  {
    Id: 6,
    firstName: "James",
    lastName: "Brown",
    email: "james@cellregenhyperbaric.com.au",
    phone: "03 9321 6547",
    company: "Cellregen Hyperbaric Oxygen",
    serviceId: 1,
    price: 499,
    billingFrequency: "monthly",
    quantity: 1,
    startDate: "2024-03-01",
    contractDuration: 12,
    status: "active",
    paymentStatus: "TBC",
    notes: "New client in specialized medical field"
  },
  {
    Id: 7,
    firstName: "Rachel",
    lastName: "Davis",
    email: "rachel@seabreezehealth.com.au",
    phone: "03 9876 9999",
    company: "Seabreeze",
    serviceId: 2,
    price: 299,
    billingFrequency: "monthly",
    quantity: 1,
    startDate: "2024-03-15",
    contractDuration: 6,
    status: "pending",
    paymentStatus: "Pending",
    notes: "Waiting for final approval from management"
  }
]